### PR TITLE
Build RPMs for HPC UGent

### PR DESCRIPTION
**Pull request by itkovian**

### CODE REVIEW

**Comment by itkovian** [comment]
This basically works ... except when Travis thinks it fails :)

**Comment by boegel** [comment]
@itkovian The failure on Travis really looks like a problem, not a fluke?

```
$ docker exec slurm-$SLURM /pyslurm/scripts/config.sh
oci runtime error: exec failed: container_linux.go:265: starting container process caused "exec: \"/pyslurm/scripts/config.sh\": stat /pyslurm/scripts/config.sh: no such file or directory"
```

**Comment by wdpypere** [comment]
@itkovian any news on this?

**Comment by wdpypere** [comment]
how does one retrigger tests?

**Comment by wdpypere** [comment]
@itkovian any news on this?

**Comment by itkovian** [comment]
Actually, all builds pass, except for the python 3.5 one.

**Comment by stdweird** [comment]
@itkovian then cut py35 too?

**Comment by boegel** [comment]
+1 on dropping Python 3.5, minimal Python version we should support is 3.6:

```
$ python3 -V
Python 3.6.8
$ which -a python3
/usr/bin/python3
$ rpm -qf /usr/bin/python3
python36-3.6.8-1.el7.x86_64
```

**Comment by wdpypere** [comment]
@itkovian can we cut python 3.5 on this? do we want this closed? merged? fixed? on hold?

**Comment by itkovian** [comment]
Closing this, will add a new PR.

**Pull request closed without merging**
